### ISSUE TITLE
FR6. Rating Posts

### ISSUE THREAD

**Issue by khalid4747** [WSU-4110/Quorum#1]
|FR6.  Rating Posts|
|---|
|**Goal**: The application will allow users to rate posts by either up-voting or down-voting the post.
**Stakeholders:** Site-wide Admins, Forum Moderator, Members|
| **Description:** Each user will be able to rate a post on a forum or a status update. Other users will be able to view the ratings but not see who rated it. Only the original poster will be able to see who up-voted or down-voted their status or forum. |
| **Origin:** Idea based on project proposal, team members came up with idea during first team meeting. |
| **Version:** 1.0  |
|**Date:** 09/23/2019|
  **Priority:** 4 |

**Comment by WameedM** [comment]
Unable to complete before live demo date
