### ISSUE TITLE
FR13. Moderate Forum

### ISSUE THREAD

**Issue by fbuggia1** [WSU-4110/Quorum#10]
|FR13. Moderate Forum|
|---|
|**Goal**: Each forum will have at least one moderator to help keep behavior respectful and to manage posts and replies.
**Stakeholders:** Site-wide Admins, Forum Moderator|
| **Description:** Each forum will have at least one moderator to manage it. The creator of each forum is the original moderator but can add more. Forums can have threads or replies removed. Threads as well as the entire forum can be locked. Users can be kicked and banned from a specific forum, and forums can be made private so as to need an invitation to be a part of it. Site-wide admins have forum moderator powers but for any and all forums.|
| **Origin:** Idea based on project proposal, team members came up with idea during second team meeting, reshaped original idea from proposal.|
| **Version:** 1.0  |  
|**Date:** 09/23/2020  
|  **Priority:** 4 |

**Comment by WameedM** [comment]
Unable to complete before live demo date
