### ISSUE TITLE
FR14. Moderate Site

### ISSUE THREAD

**Issue by KareemElmarakbyWSU** [WSU-4110/Quorum#12]
|FR14. Moderate Site|
|---|
|**Goal**: Admins will have all the privileges of moderators and will also be able to demote moderators.
**Stakeholders:** Site-wide Admins|
| **Description:** Admins will have the highest access across the website. They will be able to remove threads and comments as well as ban users and moderators, and they can also demote moderators into users. |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/23/2020|
  **Priority:** 4 |

**Comment by WameedM** [comment]
Unable to complete before live demo date
