### ISSUE TITLE
FR7. Quote Posts

### ISSUE THREAD

**Issue by AShulaiba** [WSU-4110/Quorum#17]
|FR7. Quote Posts|
|---|
|**Goal**: Let users quote/reference other posts to give context to their reply|
|**Stakeholders:**  Site-wide Admins, Forum Moderator, Members|
|**Description:** Users will be able to input a quote which will show what another user said as well as which user said it. Quote posts can quote other quote posts|
|**Origin:** Idea based on project proposal, team members came up with idea during second team meeting.|
|**Version:** 1.0|
|**Date:** 09/23/2020|  
|**Priority:** 4|

**Comment by WameedM** [comment]
Unable to complete before live demo date
