### ISSUE TITLE
FR12. Repost Status Updates

### ISSUE THREAD

**Issue by AShulaiba** [WSU-4110/Quorum#18]
|FR12. Repost Status Updates|
|---|
|**Goal**: Users will be able to repost status updates of other users or themselves|
|**Stakeholders:**  Site-wide Admins, Forum Moderator, Members|
|**Description:** Users will be able to repost status updates of users who are not private. This will also allow users to repost their own status updates even if they are private.|
|**Origin:** Idea based on project proposal, team members came up with idea during first team meeting.|
|**Version:** 1.0|
|**Date:** 09/23/2020|  
|**Priority:** 4|

**Comment by WameedM** [comment]
Unable to complete before live demo date
