### ISSUE TITLE
FR10. Post status updates

### ISSUE THREAD

**Issue by khalid4747** [WSU-4110/Quorum#2]
|FR10.  Post Status Updates|
|---|
|**Goal**: Users will be able to post a short status update independent of a forum.
**Stakeholders:** Site-wide Admins, Forum Moderator, Members|
| **Description:** A user will be able to post a quick status update where it will be limited to less than 500 characters.  Other users will be able to rate the post and interact with it by commenting. Unlike a forum these are generally shorter conversations. |
| **Origin:** Idea based on project proposal, team members came up with idea during first team meeting.|
| **Version:** 1.0  |
|**Date:** 09/23/2019|
  **Priority:** 3 |

**Comment by WameedM** [comment]
Unable to complete before live demo date
