### ISSUE TITLE
FR11. User Feed

### ISSUE THREAD

**Issue by khalid4747** [WSU-4110/Quorum#3]
|FR.11 User Feed|
|---|
|**Goal**: Users will have a personalized feed of the people that they have followed
**Stakeholders:** Site-wide Admins, Forum Moderator, Members|
| **Description:** Users will have a personalized feed of the people that they have followed. It will show recent activity of the members who the user has followed will show in their feed. This will be the home page once they have signed in. The user can click on the feed to expand a preview of the recent comments or click the thread to view the full thread. |
| **Origin:** Idea based on project proposal, team members came up with idea during first team meeting.|
| **Version:** 1.0  |
|**Date:** 09/23/2019|
  **Priority:** 3 |

**Comment by WameedM** [comment]
Unable to complete before live demo date
