### ISSUE TITLE
FR3. Private Messaging

### ISSUE THREAD

**Issue by fbuggia1** [WSU-4110/Quorum#6]
|FR3.  Private Messaging|
|---|
|**Goal**: The application will allow users to send private messages to other users.
**Stakeholders:** Site-wide Admins, Forum Moderator, Members|
| **Description:** Users will be able to speak directly and privately with other users. A user will be able to initiate a private conversation by visiting the profile of the user they wish to speak with. This conversation will only be allowed if the receiving user has a public account or a private account but given permission to the sender. All private conversations will be saved and accessible by the users who participated.|
| **Origin:** Idea was based on project proposal, team members came up with idea during first team meeting|
| **Version:** 1.0  |  
|**Date:** 09/23/2020  
|  **Priority:** 3 |

**Comment by WameedM** [comment]
Unable to complete before live demo date
