### ISSUE TITLE
FR8. Profile Page

### ISSUE THREAD

**Issue by fbuggia1** [WSU-4110/Quorum#8]
|FR8. Profile Page|
|---|
|**Goal**: Each user will have a profile page that is meant for other users to look at and access.
**Stakeholders:** Site-wide Admins, Forum Moderator, Members|
| **Description:** Every user will have a profile page. This profile page will display personal information of the users choosing. This page will also display any personal posts of the users as well as information on what forums this user is a member of. Public profiles can be viewed by any user whereas private profiles would require permission to view.|
| **Origin:** Idea based on project proposal, team members came up with idea during first team meeting|
| **Version:** 1.0  |  
|**Date:** 09/23/2020  
|  **Priority:** 3 |

**Comment by WameedM** [comment]
Partially complete
