### ISSUE TITLE
FR9. Following other users

### ISSUE THREAD

**Issue by KareemElmarakbyWSU** [WSU-4110/Quorum#9]
|FR9. Following other users|
|---|
|**Goal**: Each user will be able to follow other users.
**Stakeholders:** Site-wide Admins, Forum Moderator, Members|
| **Description:** Every user will be able to follow another user from that user’s profile page. Once a user is followed, their posts will show up in the feed of whoever followed them. A user can unfollow later on by clicking the same button (button toggles between following and not). |
| **Origin:** Based on initial project specification   document, team members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 09/23/2020|
  **Priority:** 3 |

**Comment by WameedM** [comment]
Unable to complete before live demo date
